Repository KOPO-DA5/Retro-game-console, pull requests merged in 2024-04, with the labels that each got.

#3 아까이슈 처리함
  index.html
Labels: documentation, enhancement

#5 📝 docs: add test commit
  index.html
Labels: good first issue

#9 🎉 수정완료
  index.html
Labels: documentation

#12 🎨 feat : 기능 추가
  index.html
Labels: documentation, enhancement

#15 간단한 SPA 코드 추가
  css/common.css
  css/dianosaur.css
  dinosaur.html
  index.html
  js/dianosaur.js
  js/test.js
Labels: 💫 feat

#17 🧪 test : 웹훅 테스트
  index.html
Labels: ✅ test

#23 ✅ test : 테스트
  js/dianosaur.js
Labels: ✅ test

#24 [feat] 테트리스 게임 컨네이너 및 play 버튼 추가
  css/common.css
  css/tetris.css
  index.html
  js/test.js
  js/tetris.js
  js/tetris/board.js
  js/tetris/constants.js
  js/tetris/main.js
Labels: 💫 feat, Priority: High

#27 25 테트리스 블록 랜덤 생성 및 크기 조정 기능
  js/tetris.js
  js/tetris/board.js
  js/tetris/constants.js
  js/tetris/main.js
  js/tetris/piece.js
Labels: 💫 feat, Priority: High

#33 🎨 feat : 분리 완료
  css/common.css
  css/dianosaur.css
  css/dinosaur.css
  css/tetris.css
  dinosaur.html
  images/dinosaur/cactus.png
  images/dinosaur/dino-lose.png
  images/dinosaur/dino-run-0.png
  images/dinosaur/dino-run-1.png
  images/dinosaur/dino-stationary.png
  images/dinosaur/dinosaur.png
  images/dinosaur/ground.png
  index.html
  js/app.js
  js/dianosaur.js
  js/dinosaur.js
  js/dinosaur/main.js
  js/tetris.js
  tetris.html
Labels: 💫 feat, Priority: High

#35 34 feat 게임간 화면 선택창 버튼 화면 내부로 이동 등
  css/common.css
  css/dinosaur.css
  css/tetris.css
  index.html
  js/app.js
  js/dinosaur.js
  js/tetris.js
Labels: 💫 feat, Priority: High

#37 feat : 게임 선택 화면 구현 완료
  css/common.css
  css/dinosaur.css
  index.html
  js/app.js
Labels: 💫 feat, Priority: High

#40 ✨ feat : 일시정기능 거의 다 완성
  css/common.css
  css/dinosaur.css
  js/app.js
  js/dinosaur.js
  js/dinosaur/main.js
  js/tetris.js
Labels: 💫 feat

#41 36 테트리스 블록 애니메이션 및 회전 기능
  js/tetris.js
  js/tetris/board.js
  js/tetris/main.js
  js/tetris/piece.js
Labels: 💫 feat, Priority: High

#43 42 feat 테트리스 점수 계산 및 난이도 조절
  js/tetris/board.js
  js/tetris/constants.js
  js/tetris/main.js
Labels: 💫 feat, Priority: High

#47 46 feat 사용자명 스코어 랭킹에 저장
  css/tetris.css
  js/tetris.js
  js/tetris/constants.js
  js/tetris/main.js
Labels: 💫 feat, Priority: High

#53 48 feat 테트리스 배경음 및 소리 삽입
  audios/tetris/drop.mp3
  audios/tetris/levelUp.mp3
  audios/tetris/remove-line.mp3
  audios/tetris/tetris-background.mp3
  audios/tetris/tetris-finish.mp3
  css/tetris.css
  js/tetris.js
  js/tetris/board.js
  js/tetris/constants.js
  js/tetris/main.js
  js/tetris/sound.js
Labels: 💫 feat, Priority: High

#55 38 feat 일시정지 기능 및 화면
  .vscode/settings.json
  index.html
  js/app.js
  js/dinosaur.js
  js/dinosaur/main.js
Labels: 🐛 bug

#58 52 feat 게임 선택창 화면 및 기능 구현
  css/dinosaur.css
  images/dinosaur/kirby/kirby-jump.png
  images/dinosaur/kirby/kirby-lose.png
  images/dinosaur/kirby/kirby-run-0.png
  images/dinosaur/kirby/kirby-run-1.png
  images/dinosaur/kirby/kirby-run-2.png
  images/dinosaur/kirby/kirby-run-3.png
  images/dinosaur/kirby/kirby-stationary.png
  images/dinosaur/mario/mario-jump.png
  images/dinosaur/mario/mario-lose.png
  images/dinosaur/mario/mario-run-0.png
  images/dinosaur/mario/mario-run-1.png
  images/dinosaur/mario/mario-run-2.png
  images/dinosaur/mario/mario-run-3.png
  images/dinosaur/mario/mario-stationary.png
  index.html
  js/app.js
  js/dinosaur.js
  js/dinosaur/dinosaur.js
  js/dinosaur/main.js
  js/dinosaur/skin.js
Labels: 💫 feat, Priority: High

#59 56 feat 공룡게임 랭킹 기능 사용자명 입력 로컬 스토리지 저장 -> 변경사항 많음
  .vscode/settings.json
  css/common.css
  css/dinosaur.css
  index.html
  js/app.js
  js/dinosaur/dinosaur.js
  js/dinosaur/main.js
  js/dinosaur/skin.js
  js/globalState.js
  js/tetris/main.js
  test.html
Labels: 🐛 bug, 💫 feat, ♻️ refactor

#63 🐛 fix : 오디오, 이미지 버그 해결
  js/app.js
  js/dinosaur/dinosaur.js
  js/dinosaur/main.js
  js/dinosaur/skin.js
Labels: 🐛 bug, Priority: High

#66 ✨ feat: 조이스틱, 버튼 애니메이션 수정
  css/common.css
  js/app.js
  js/dinosaur/main.js
  js/dinosaur/skin.js
  js/gameControler.js
  js/tetris/main.js
Labels: 💫 feat, Priority: High

#70 68 feat 테트리스 크기 변경 및 랭킹 화면
  css/tetris.css
  js/app.js
  js/tetris.js
  js/tetris/constants.js
  js/tetris/main.js
Labels: 💫 feat, Priority: High

#72 ✨ feat: 코인 기능 추가
  js/app.js
  js/coin.js
  js/dinosaur/dinosaur.js
  js/dinosaur/main.js
  js/tetris.js
  js/tetris/main.js
Labels: 💫 feat, Priority: High

#75 73 fix 게임기 화면에 공룡게임 맞추기
  css/common.css
  css/dinosaur.css
  index.html
  js/dinosaur/dinosaur.js
Labels: 🐛 bug

#79 ✨ feat : 공룡 게임 스킨 추가, 오디오 관련 오류 수정
  images/dinosaur/mushroom/mushroom-jump.png
  images/dinosaur/mushroom/mushroom-lose.png
  images/dinosaur/mushroom/mushroom-run-0.png
  images/dinosaur/mushroom/mushroom-run-1.png
  images/dinosaur/mushroom/mushroom-run-2.png
  images/dinosaur/mushroom/mushroom-run-3.png
  images/dinosaur/mushroom/mushroom-stationary.png
  index.html
  js/app.js
  js/dinosaur/skin.js
Labels: 🐛 bug, 💫 feat, Priority: High

#80 77 feat 메인화면 및 게임 선택 화면 디자인 수정 애니메이션 추가
  css/common.css
  images/main/arcade_background_img_2.jpeg
  images/main/game-display-1.gif
  images/main/game-display-2.gif
  index.html
  js/app.js
  js/dinosaur/main.js
  js/tetris.js
Labels: 💫 feat, Priority: High

#84 🐛 fix : 각종 버그 수정
  css/common.css
  css/tetris.css
  index.html
  js/app.js
  js/dinosaur/main.js
  js/globalState.js
  js/tetris.js
  js/tetris/constants.js
  js/tetris/main.js
  js/tetris/piece.js
  test.html
Labels: 🐛 bug, Priority: High

#85 🐛 fix : 테트리스 재시작 가능
  index.html
  js/tetris.js
  js/tetris/board.js
  js/tetris/constants.js
  js/tetris/main.js
  js/tetris/piece.js
  js/tetris/sound.js
Labels: 🐛 bug

#92 [fix] : 한줄깨기 버그 수정
  css/tetris.css
  index.html
  js/tetris/main.js
Labels: 🐛 bug

#95 90 feat 코인 insert 기능 수정 css 디자인 수정
  css/common.css
  css/dinosaur.css
  css/tetris.css
  images/main/arcade_background_img_3.jpeg
  js/app.js
  js/dinosaur/dinosaur.js
  js/dinosaur/main.js
  js/tetris.js
  js/tetris/main.js
Labels: 💫 feat, Priority: High

#98 거의 완성입니다~~ 다들 고생했어요!
  index.html
  js/app.js
  js/dinosaur/main.js
  js/tetris/main.js
Labels: Priority: High

#100 99 feat 카운트 다운 화면 사운드 추가
  audios/else/countdown-sound.mp3
  js/dinosaur/dinosaur.js
  js/dinosaur/main.js
  js/tetris/main.js
  js/tetris/sound.js
Labels: 💫 feat, Priority: Medium
